language: ruby

script: "bundle exec rake test"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - 2.3.1
gemfile:
  - Gemfile-Rails-3.x
  - Gemfile-Rails-4.x
  - Gemfile
matrix:
  exclude:
    - rvm: 2.2.3
      gemfile: Gemfile-Rails-3.x
    - rvm: 2.3.1
      gemfile: Gemfile-Rails-3.x
    - rvm: 1.9.3
      gemfile: Gemfile-Rails-4.x
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.0.0
      gemfile: Gemfile
    - rvm: 2.1.7
      gemfile: Gemfile
