safe:        true
baseurl:     /
url: http://localhost:4000

source:      .
destination: ./_site

future:      true
lsi:         false
highlighter: rouge
markdown:    redcarpet
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: [no_intra_emphasis]

kramdown:
  input: GFM
  css_class: highlight
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  syntax_highlighter_opts:
    wrap: div
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
    tab_width: 4
    bold_every: 10
    css: style

nav_items:
- url: /
  text: Start page
  nav_id: start_page
- url: /pages/example_application.html
  text: Example application
  nav_id: example_application
- url: /pages/active_record_model_api.html
  text: Model API
  nav_id: model_api
- url: /pages/action_controller_api.html
  text: Controller API
  nav_id: controller_api
- url: /pages/action_view_api.html
  text: View API
  nav_id: view_api
- url: /pages/active_record_scope_patterns.html
  text: Scope patterns
  nav_id: scope_patterns
- url: https://github.com/jhund/filterrific
  text: Source
  nav_id: source
